name: texas_covid
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.9.0
  - dash=1.11.0
  - google-cloud-storage=1.30.0
  - ipywidgets=7.5.1
  - jupyterlab=2.1.5
  - matplotlib=3.2.1
  - numpy=1.19.0
  - pandas=1.0.5
  - pip=20.0.2
  - plotly=4.6.0
  - pymc3=3.9.2
  - python=3.7.6
  - scipy=1.5.0
  - xlrd=1.2.0
